ALTER TABLE "user_addresses" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "mfa_codes" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "access_requests" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "payment_transactions" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "providers" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "patients" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "provider_patient_mappings" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "appointments" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "provider_availability" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "provider_availability_exceptions" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "app_settings" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "provider_settings" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "encounters" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "medications" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "conditions" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "allergies" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "vitals" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "emr_orders" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "addendums" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "billing_diagnoses" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "billing_groups" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "billing_procedures" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "patient_documents" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "prescriptions" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "medication_catalog" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "pharmacies" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "pharmacy_backends" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "pharmacy_medications" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "provider_pharmacy_links" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "pharmacy_admins" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "tiers" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "system_logs" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "goal_progress" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "goals" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "resources" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "tags" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "notification_actions" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "notifications" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "order_activities" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "order_line_items" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "orders" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "categories" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "products" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "symptoms" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "provider_patient_mappings" DROP CONSTRAINT "provider_patient_unique";
DROP INDEX "idx_provider_patient_mappings_provider_id";
DROP INDEX "idx_provider_patient_mappings_patient_id";
ALTER TABLE "provider_pharmacy_links" DROP CONSTRAINT "provider_pharmacy_links_provider_id_pharmacy_id_pk";
ALTER TABLE "pharmacy_admins" DROP CONSTRAINT "pharmacy_admins_user_id_pharmacy_id_pk";
DROP POLICY "user_addresses_select_policy" ON "user_addresses" CASCADE;
DROP POLICY "user_addresses_insert_policy" ON "user_addresses" CASCADE;
DROP POLICY "user_addresses_update_policy" ON "user_addresses" CASCADE;
DROP POLICY "user_addresses_delete_policy" ON "user_addresses" CASCADE;
DROP POLICY "mfa_codes_select_policy" ON "mfa_codes" CASCADE;
DROP POLICY "mfa_codes_insert_policy" ON "mfa_codes" CASCADE;
DROP POLICY "mfa_codes_update_policy" ON "mfa_codes" CASCADE;
DROP POLICY "mfa_codes_delete_policy" ON "mfa_codes" CASCADE;
DROP POLICY "access_requests_select_policy" ON "access_requests" CASCADE;
DROP POLICY "access_requests_insert_policy" ON "access_requests" CASCADE;
DROP POLICY "access_requests_update_policy" ON "access_requests" CASCADE;
DROP POLICY "access_requests_delete_policy" ON "access_requests" CASCADE;
DROP POLICY "payment_transactions_select_policy" ON "payment_transactions" CASCADE;
DROP POLICY "payment_transactions_insert_policy" ON "payment_transactions" CASCADE;
DROP POLICY "payment_transactions_update_policy" ON "payment_transactions" CASCADE;
DROP POLICY "payment_transactions_delete_policy" ON "payment_transactions" CASCADE;
DROP POLICY "providers_select_policy" ON "providers" CASCADE;
DROP POLICY "providers_insert_policy" ON "providers" CASCADE;
DROP POLICY "providers_update_policy" ON "providers" CASCADE;
DROP POLICY "providers_delete_policy" ON "providers" CASCADE;
DROP POLICY "patients_select_policy" ON "patients" CASCADE;
DROP POLICY "patients_insert_policy" ON "patients" CASCADE;
DROP POLICY "patients_update_policy" ON "patients" CASCADE;
DROP POLICY "patients_delete_policy" ON "patients" CASCADE;
DROP POLICY "ppm_select_policy" ON "provider_patient_mappings" CASCADE;
DROP POLICY "ppm_insert_policy" ON "provider_patient_mappings" CASCADE;
DROP POLICY "ppm_update_policy" ON "provider_patient_mappings" CASCADE;
DROP POLICY "ppm_delete_policy" ON "provider_patient_mappings" CASCADE;
DROP POLICY "appointments_select_policy" ON "appointments" CASCADE;
DROP POLICY "appointments_insert_policy" ON "appointments" CASCADE;
DROP POLICY "appointments_update_policy" ON "appointments" CASCADE;
DROP POLICY "appointments_delete_policy" ON "appointments" CASCADE;
DROP POLICY "provider_availability_select_policy" ON "provider_availability" CASCADE;
DROP POLICY "provider_availability_insert_policy" ON "provider_availability" CASCADE;
DROP POLICY "provider_availability_update_policy" ON "provider_availability" CASCADE;
DROP POLICY "provider_availability_delete_policy" ON "provider_availability" CASCADE;
DROP POLICY "provider_availability_exceptions_select_policy" ON "provider_availability_exceptions" CASCADE;
DROP POLICY "provider_availability_exceptions_insert_policy" ON "provider_availability_exceptions" CASCADE;
DROP POLICY "provider_availability_exceptions_update_policy" ON "provider_availability_exceptions" CASCADE;
DROP POLICY "provider_availability_exceptions_delete_policy" ON "provider_availability_exceptions" CASCADE;
DROP POLICY "app_settings_select_policy" ON "app_settings" CASCADE;
DROP POLICY "app_settings_insert_policy" ON "app_settings" CASCADE;
DROP POLICY "app_settings_update_policy" ON "app_settings" CASCADE;
DROP POLICY "app_settings_delete_policy" ON "app_settings" CASCADE;
DROP POLICY "provider_settings_select_policy" ON "provider_settings" CASCADE;
DROP POLICY "provider_settings_insert_policy" ON "provider_settings" CASCADE;
DROP POLICY "provider_settings_update_policy" ON "provider_settings" CASCADE;
DROP POLICY "provider_settings_delete_policy" ON "provider_settings" CASCADE;
DROP POLICY "encounters_select_policy" ON "encounters" CASCADE;
DROP POLICY "encounters_insert_policy" ON "encounters" CASCADE;
DROP POLICY "encounters_update_policy" ON "encounters" CASCADE;
DROP POLICY "encounters_delete_policy" ON "encounters" CASCADE;
DROP POLICY "medications_select_policy" ON "medications" CASCADE;
DROP POLICY "medications_insert_policy" ON "medications" CASCADE;
DROP POLICY "medications_update_policy" ON "medications" CASCADE;
DROP POLICY "medications_delete_policy" ON "medications" CASCADE;
DROP POLICY "conditions_select_policy" ON "conditions" CASCADE;
DROP POLICY "conditions_insert_policy" ON "conditions" CASCADE;
DROP POLICY "conditions_update_policy" ON "conditions" CASCADE;
DROP POLICY "conditions_delete_policy" ON "conditions" CASCADE;
DROP POLICY "allergies_select_policy" ON "allergies" CASCADE;
DROP POLICY "allergies_insert_policy" ON "allergies" CASCADE;
DROP POLICY "allergies_update_policy" ON "allergies" CASCADE;
DROP POLICY "allergies_delete_policy" ON "allergies" CASCADE;
DROP POLICY "vitals_select_policy" ON "vitals" CASCADE;
DROP POLICY "vitals_insert_policy" ON "vitals" CASCADE;
DROP POLICY "vitals_update_policy" ON "vitals" CASCADE;
DROP POLICY "vitals_delete_policy" ON "vitals" CASCADE;
DROP POLICY "emr_orders_select_policy" ON "emr_orders" CASCADE;
DROP POLICY "emr_orders_insert_policy" ON "emr_orders" CASCADE;
DROP POLICY "emr_orders_update_policy" ON "emr_orders" CASCADE;
DROP POLICY "emr_orders_delete_policy" ON "emr_orders" CASCADE;
DROP POLICY "addendums_select_policy" ON "addendums" CASCADE;
DROP POLICY "addendums_insert_policy" ON "addendums" CASCADE;
DROP POLICY "addendums_update_policy" ON "addendums" CASCADE;
DROP POLICY "addendums_delete_policy" ON "addendums" CASCADE;
DROP POLICY "billing_diagnoses_select_policy" ON "billing_diagnoses" CASCADE;
DROP POLICY "billing_diagnoses_insert_policy" ON "billing_diagnoses" CASCADE;
DROP POLICY "billing_diagnoses_update_policy" ON "billing_diagnoses" CASCADE;
DROP POLICY "billing_diagnoses_delete_policy" ON "billing_diagnoses" CASCADE;
DROP POLICY "billing_groups_select_policy" ON "billing_groups" CASCADE;
DROP POLICY "billing_groups_insert_policy" ON "billing_groups" CASCADE;
DROP POLICY "billing_groups_update_policy" ON "billing_groups" CASCADE;
DROP POLICY "billing_groups_delete_policy" ON "billing_groups" CASCADE;
DROP POLICY "billing_procedures_select_policy" ON "billing_procedures" CASCADE;
DROP POLICY "billing_procedures_insert_policy" ON "billing_procedures" CASCADE;
DROP POLICY "billing_procedures_update_policy" ON "billing_procedures" CASCADE;
DROP POLICY "billing_procedures_delete_policy" ON "billing_procedures" CASCADE;
DROP POLICY "patient_documents_select_policy" ON "patient_documents" CASCADE;
DROP POLICY "patient_documents_insert_policy" ON "patient_documents" CASCADE;
DROP POLICY "patient_documents_update_policy" ON "patient_documents" CASCADE;
DROP POLICY "patient_documents_delete_policy" ON "patient_documents" CASCADE;
DROP POLICY "prescriptions_select_policy" ON "prescriptions" CASCADE;
DROP POLICY "prescriptions_insert_policy" ON "prescriptions" CASCADE;
DROP POLICY "prescriptions_update_policy" ON "prescriptions" CASCADE;
DROP POLICY "prescriptions_delete_policy" ON "prescriptions" CASCADE;
DROP POLICY "medication_catalog_select_policy" ON "medication_catalog" CASCADE;
DROP POLICY "medication_catalog_insert_policy" ON "medication_catalog" CASCADE;
DROP POLICY "medication_catalog_update_policy" ON "medication_catalog" CASCADE;
DROP POLICY "medication_catalog_delete_policy" ON "medication_catalog" CASCADE;
DROP POLICY "pharmacies_select_policy" ON "pharmacies" CASCADE;
DROP POLICY "pharmacies_insert_policy" ON "pharmacies" CASCADE;
DROP POLICY "pharmacies_update_policy" ON "pharmacies" CASCADE;
DROP POLICY "pharmacies_delete_policy" ON "pharmacies" CASCADE;
DROP POLICY "pharmacy_backends_select_policy" ON "pharmacy_backends" CASCADE;
DROP POLICY "pharmacy_backends_insert_policy" ON "pharmacy_backends" CASCADE;
DROP POLICY "pharmacy_backends_update_policy" ON "pharmacy_backends" CASCADE;
DROP POLICY "pharmacy_backends_delete_policy" ON "pharmacy_backends" CASCADE;
DROP POLICY "pharmacy_medications_select_policy" ON "pharmacy_medications" CASCADE;
DROP POLICY "pharmacy_medications_insert_policy" ON "pharmacy_medications" CASCADE;
DROP POLICY "pharmacy_medications_update_policy" ON "pharmacy_medications" CASCADE;
DROP POLICY "pharmacy_medications_delete_policy" ON "pharmacy_medications" CASCADE;
DROP POLICY "provider_pharmacy_links_select_policy" ON "provider_pharmacy_links" CASCADE;
DROP POLICY "provider_pharmacy_links_insert_policy" ON "provider_pharmacy_links" CASCADE;
DROP POLICY "provider_pharmacy_links_update_policy" ON "provider_pharmacy_links" CASCADE;
DROP POLICY "provider_pharmacy_links_delete_policy" ON "provider_pharmacy_links" CASCADE;
DROP POLICY "pharmacy_admins_select_policy" ON "pharmacy_admins" CASCADE;
DROP POLICY "pharmacy_admins_insert_policy" ON "pharmacy_admins" CASCADE;
DROP POLICY "pharmacy_admins_update_policy" ON "pharmacy_admins" CASCADE;
DROP POLICY "pharmacy_admins_delete_policy" ON "pharmacy_admins" CASCADE;
DROP POLICY "tiers_select_policy" ON "tiers" CASCADE;
DROP POLICY "tiers_insert_policy" ON "tiers" CASCADE;
DROP POLICY "tiers_update_policy" ON "tiers" CASCADE;
DROP POLICY "tiers_delete_policy" ON "tiers" CASCADE;
DROP POLICY "system_logs_select_policy" ON "system_logs" CASCADE;
DROP POLICY "system_logs_insert_policy" ON "system_logs" CASCADE;
DROP POLICY "system_logs_update_policy" ON "system_logs" CASCADE;
DROP POLICY "system_logs_delete_policy" ON "system_logs" CASCADE;
DROP POLICY "goal_progress_select_policy" ON "goal_progress" CASCADE;
DROP POLICY "goal_progress_insert_policy" ON "goal_progress" CASCADE;
DROP POLICY "goal_progress_update_policy" ON "goal_progress" CASCADE;
DROP POLICY "goal_progress_delete_policy" ON "goal_progress" CASCADE;
DROP POLICY "goals_select_policy" ON "goals" CASCADE;
DROP POLICY "goals_insert_policy" ON "goals" CASCADE;
DROP POLICY "goals_update_policy" ON "goals" CASCADE;
DROP POLICY "goals_delete_policy" ON "goals" CASCADE;
DROP POLICY "resources_select_policy" ON "resources" CASCADE;
DROP POLICY "resources_insert_policy" ON "resources" CASCADE;
DROP POLICY "resources_update_policy" ON "resources" CASCADE;
DROP POLICY "resources_delete_policy" ON "resources" CASCADE;
DROP POLICY "tags_select_policy" ON "tags" CASCADE;
DROP POLICY "tags_insert_policy" ON "tags" CASCADE;
DROP POLICY "tags_update_policy" ON "tags" CASCADE;
DROP POLICY "tags_delete_policy" ON "tags" CASCADE;
DROP POLICY "notification_actions_select_policy" ON "notification_actions" CASCADE;
DROP POLICY "notification_actions_insert_policy" ON "notification_actions" CASCADE;
DROP POLICY "notification_actions_update_policy" ON "notification_actions" CASCADE;
DROP POLICY "notification_actions_delete_policy" ON "notification_actions" CASCADE;
DROP POLICY "notifications_select_policy" ON "notifications" CASCADE;
DROP POLICY "notifications_insert_policy" ON "notifications" CASCADE;
DROP POLICY "notifications_update_policy" ON "notifications" CASCADE;
DROP POLICY "notifications_delete_policy" ON "notifications" CASCADE;
DROP POLICY "order_activities_select_policy" ON "order_activities" CASCADE;
DROP POLICY "order_activities_insert_policy" ON "order_activities" CASCADE;
DROP POLICY "order_activities_update_policy" ON "order_activities" CASCADE;
DROP POLICY "order_activities_delete_policy" ON "order_activities" CASCADE;
DROP POLICY "order_line_items_select_policy" ON "order_line_items" CASCADE;
DROP POLICY "order_line_items_insert_policy" ON "order_line_items" CASCADE;
DROP POLICY "order_line_items_update_policy" ON "order_line_items" CASCADE;
DROP POLICY "order_line_items_delete_policy" ON "order_line_items" CASCADE;
DROP POLICY "orders_select_policy" ON "orders" CASCADE;
DROP POLICY "orders_insert_policy" ON "orders" CASCADE;
DROP POLICY "orders_update_policy" ON "orders" CASCADE;
DROP POLICY "orders_delete_policy" ON "orders" CASCADE;
DROP POLICY "categories_select_policy" ON "categories" CASCADE;
DROP POLICY "categories_insert_policy" ON "categories" CASCADE;
DROP POLICY "categories_update_policy" ON "categories" CASCADE;
DROP POLICY "categories_delete_policy" ON "categories" CASCADE;
DROP POLICY "products_select_policy" ON "products" CASCADE;
DROP POLICY "products_insert_policy" ON "products" CASCADE;
DROP POLICY "products_update_policy" ON "products" CASCADE;
DROP POLICY "products_delete_policy" ON "products" CASCADE;
DROP POLICY "symptoms_select_policy" ON "symptoms" CASCADE;
DROP POLICY "symptoms_insert_policy" ON "symptoms" CASCADE;
DROP POLICY "symptoms_update_policy" ON "symptoms" CASCADE;
DROP POLICY "symptoms_delete_policy" ON "symptoms" CASCADE;