/**
 * regenerate-stale-pdf.ts — auto-upgrade pre-May-1-2026 prescription PDFs.
 *
 * Background (Keith Robinson incident, May 7 2026):
 *   The Greenwich Electronic Rx visual template shipped 2026-05-01 22:43 UTC
 *   (commit b899ed0 "Task #37: Greenwich Rx PDF template redesign"). Brand-new
 *   prescriptions created on/after that date are generated with the new
 *   template at creation time. But prescriptions created BEFORE that date,
 *   if they were stuck in pending_payment past May 1 and only got pushed to
 *   the pharmacy later (e.g. via the orphan-heal sweeper), would ship the
 *   old-format PDF that was sitting in storage from April.
 *
 *   This helper detects that situation by parsing the timestamp embedded
 *   in the storage path filename (`prescriptions/{patientId}/{rxId}/{ms}.pdf`)
 *   and, if older than the cutoff, regenerates the PDF using the current
 *   template, uploads it, updates `pdf_storage_path`, and returns the new
 *   path. The caller then downloads the FRESH PDF and ships it to the
 *   pharmacy as part of its normal flow.
 *
 *   Scope: ONLY runs when `isGreenwichPharmacy(pharmacyId)` is true, since
 *   the redesigned template is Greenwich-specific. Other pharmacies are
 *   left untouched.
 *
 *   Failure mode: if regeneration fails for any reason, the helper returns
 *   the ORIGINAL storage path (never null) so the submission still proceeds
 *   with the old PDF — Greenwich receiving an old-format PDF is bad but
 *   strictly better than receiving none at all.
 */

import type { SupabaseClient } from "@supabase/supabase-js";
import postgres from "postgres";
import { generatePrescriptionPdf } from "@/utils/generatePrescriptionPdf";
import { uploadPrescriptionPdf } from "@core/services/storage/prescriptionPdfStorage";
import {
  GREENWICH_CLINIC_NAME,
  isGreenwichPharmacy,
  formatBillToNote,
  classifyDosageForm,
  quantityInMl,
  quantityForOral,
  daysSupplyFromVialCount,
  daysSupplyForOral,
} from "@core/utils/digitalrx-format";

// 2026-05-01 22:43:56 UTC — when the new Greenwich Rx template went live.
// PDFs whose embedded filename timestamp is BEFORE this are pre-redesign.
const NEW_TEMPLATE_CUTOFF_MS = Date.UTC(2026, 4, 1, 22, 43, 56);

// Trevor Haynes incident, May 7 2026. Image-only "JPEG-in-PDF" wrappers
// (created when a provider uses the Step 1 file upload with a phone scan)
// were 73-124KB. Every legitimate Electronic Rx generated by
// generatePrescriptionPdf is >= 593KB (the smallest provider signature
// image we have on file is Daniel Omire Mayor's at ~593KB). 200KB is a
// safe floor: anything below that is guaranteed to be the bug pattern,
// not a legit Rx. NEVER raise this without auditing every provider's
// signature footprint first — false positives here force-regenerate
// real prescriptions in the submit hot path.
const HEALTHY_PDF_MIN_BYTES = 200_000;

/**
 * Parse the millisecond timestamp embedded in a prescription PDF path of
 * the form `prescriptions/{patientId}/{prescriptionId}/{timestamp}.pdf`.
 * Returns null if the path doesn't match the expected shape.
 */
function parsePdfTimestampMs(storagePath: string): number | null {
  const match = storagePath.match(/\/(\d{10,16})\.pdf$/i);
  if (!match) return null;
  const ms = Number(match[1]);
  return Number.isFinite(ms) && ms > 0 ? ms : null;
}

export interface StalePdfResult {
  storagePath: string;
  regenerated: boolean;
  reason?: string;
}

/**
 * If the prescription's stored PDF was generated BEFORE the May 1 2026
 * Greenwich template redesign AND the destination pharmacy is Greenwich,
 * regenerate the PDF in the new format, upload it, and update
 * `prescriptions.pdf_storage_path`. Returns the path that should be used
 * for the upcoming submission (either the fresh regenerated path, or the
 * original path if no regeneration was needed/possible).
 */
export async function ensureFreshGreenwichPdf(
  supabase: SupabaseClient,
  prescriptionId: string,
  currentStoragePath: string,
  pharmacyId: string | null | undefined,
): Promise<StalePdfResult> {
  // Only Greenwich gets the new template treatment.
  if (!pharmacyId || !isGreenwichPharmacy(pharmacyId)) {
    return { storagePath: currentStoragePath, regenerated: false, reason: "not_greenwich" };
  }

  const tsMs = parsePdfTimestampMs(currentStoragePath);
  if (tsMs === null) {
    // Unknown path shape — don't try to be clever, just keep what we have.
    return { storagePath: currentStoragePath, regenerated: false, reason: "unparseable_path" };
  }
  if (tsMs >= NEW_TEMPLATE_CUTOFF_MS) {
    return { storagePath: currentStoragePath, regenerated: false, reason: "already_fresh" };
  }

  // Stale → regenerate. Wrap everything in try/catch so a regeneration
  // failure NEVER blocks the underlying submission.
  return regenerateGreenwichPdfFromRow(
    supabase,
    prescriptionId,
    currentStoragePath,
    `stale_pre_may1 oldTsMs=${tsMs}`,
  );
}

/**
 * Internal: rebuild the Electronic Rx for a given prescription using the
 * current generatePrescriptionPdf template, upload it, and return the new
 * storage path. NEVER throws — wraps everything so callers in the submit
 * hot path stay non-blocking. On any failure the original currentStoragePath
 * is returned so the caller's submission can still proceed with whatever
 * file was already in storage.
 */
async function regenerateGreenwichPdfFromRow(
  supabase: SupabaseClient,
  prescriptionId: string,
  currentStoragePath: string,
  reasonTag: string,
): Promise<StalePdfResult> {
  try {
    const { data: rx, error: rxErr } = await supabase
      .from("prescriptions")
      .select(
        "id, patient_id, prescriber_id, submitted_by_delegation_id, medication, medication_id, quantity, refills, sig, pharmacy_notes, dispense_as_written, pharmacy_id",
      )
      .eq("id", prescriptionId)
      .single();
    if (rxErr || !rx) {
      return { storagePath: currentStoragePath, regenerated: false, reason: `rx_load_failed:${rxErr?.message || "missing"}` };
    }

    // Manning-incident fix (May 9 2026): for delegate submissions we MUST
    // load the AUTHORIZING provider's row, not the assistant's. The
    // assistant's providers row exists but has NPI / DEA / signature_url
    // all NULL — rendering it produced a 7,485-byte stub PDF that hit
    // the 200KB hard-gate and looped forever.
    const { resolveAuthorizingProvider } = await import(
      "@core/services/authorizing-provider"
    );
    const [{ data: patient }, authProvider] = await Promise.all([
      supabase
        .from("patients")
        .select("first_name, last_name, date_of_birth, data, physical_address, phone")
        .eq("id", rx.patient_id)
        .single(),
      resolveAuthorizingProvider(supabase, {
        prescriberId: rx.prescriber_id,
        delegationId: rx.submitted_by_delegation_id,
      }),
    ]);
    if (!patient || !authProvider) {
      // Audit so the operator can see WHY the regen produced no PDF —
      // most often this is a delegation row that vanished or never had
      // a valid providers join.
      try {
        await supabase.from("system_logs").insert({
          action: "PRESCRIPTION_PDF_AUTH_PROVIDER_MISSING",
          status: "error",
          details: `prescriptionId=${prescriptionId} prescriberId=${rx.prescriber_id} delegationId=${rx.submitted_by_delegation_id || "none"} patientLoaded=${!!patient} providerResolved=${!!authProvider}`,
        });
      } catch { /* logging best-effort */ }
      return { storagePath: currentStoragePath, regenerated: false, reason: "patient_or_provider_missing" };
    }
    const provider = authProvider.provider;
    if (authProvider.viaDelegation) {
      try {
        await supabase.from("system_logs").insert({
          action: "PRESCRIPTION_PDF_DELEGATE_RESOLVED",
          status: "info",
          details: `prescriptionId=${prescriptionId} delegationId=${authProvider.delegationId} authProviderUserId=${provider.user_id} hasNpi=${!!provider.npi_number} hasDea=${!!provider.dea_number} hasSig=${!!provider.signature_url}`,
        });
      } catch { /* logging best-effort */ }
    }

    const patientAddress = (patient.physical_address || {}) as Record<string, string | undefined>;
    const providerAddress = (provider.physical_address || {}) as Record<string, string | undefined>;
    const patientData = (patient.data || {}) as Record<string, string | undefined>;

    // Mirror resend-rejected.ts catalog enrichment so the regenerated PDF
    // matches what a fresh-issue prescription would produce.
    let catalogDrugName: string | undefined;
    let catalogNdc: string | undefined;
    let greenwichQty: string | undefined;
    let greenwichDaysSupply: string | undefined;
    let greenwichNotes: string | undefined;
    if (rx.medication_id) {
      const { data: med } = await supabase
        .from("pharmacy_medications")
        .select("name, ndc, vial_size, form")
        .eq("id", rx.medication_id)
        .maybeSingle();
      if (med) {
        catalogDrugName = med.name ?? undefined;
        catalogNdc = med.ndc ?? undefined;
        const vialCount = Number(rx.quantity);
        if (med.vial_size && Number.isFinite(vialCount) && vialCount > 0) {
          let formBucket: "injection" | "capsule" | "tablet" = "injection";
          try { formBucket = classifyDosageForm(med.form); } catch { /* default */ }
          try {
            greenwichQty = formBucket === "injection"
              ? quantityInMl(vialCount, med.vial_size).toString()
              : quantityForOral(vialCount, med.vial_size).toString();
          } catch { /* fall through */ }
          try {
            greenwichDaysSupply = formBucket === "injection"
              ? String(daysSupplyFromVialCount(vialCount))
              : String(daysSupplyForOral(vialCount));
          } catch { /* fall through */ }
        }
        const billToLine = formatBillToNote(GREENWICH_CLINIC_NAME);
        const existingNotes = (rx.pharmacy_notes || "").trim();
        greenwichNotes = existingNotes ? `${existingNotes}\n${billToLine}` : billToLine;
      }
    }

    const { blob, filename } = await generatePrescriptionPdf({
      patient: {
        firstName: patient.first_name || "",
        lastName: patient.last_name || "",
        dob: patient.date_of_birth || "",
        sex: patientData.gender || "U",
        street: patientAddress.street,
        city: patientAddress.city,
        state: patientAddress.state,
        zip: patientAddress.zipCode || patientAddress.zip,
        phone: patient.phone || undefined,
      },
      doctor: {
        prefix: provider.prefix || "Dr.",
        firstName: provider.first_name || "",
        lastName: provider.last_name || "",
        npi: provider.npi_number || "",
        dea: provider.dea_number || undefined,
        companyName: provider.company_name || undefined,
        street: providerAddress.street,
        city: providerAddress.city,
        state: providerAddress.state,
        zip: providerAddress.zipCode || providerAddress.zip,
        phone: provider.phone_number || undefined,
      },
      rx: {
        drugName: rx.medication || "",
        useGreenwichFormat: !!catalogDrugName,
        catalogDrugName,
        ndc: catalogNdc,
        qty: greenwichQty || String(rx.quantity || ""),
        daysSupply: greenwichDaysSupply,
        dateWritten: new Date().toISOString().split("T")[0],
        refills: String(rx.refills || "0"),
        instructions: rx.sig || undefined,
        notes: greenwichNotes || rx.pharmacy_notes || undefined,
        daw: rx.dispense_as_written ? "Y" : "N",
        pon: rx.id.slice(-8).toUpperCase(),
      },
      signatureUrl: provider.signature_url || undefined,
    });

    const arrayBuffer = await blob.arrayBuffer();
    const file = Object.assign(
      new Blob([arrayBuffer], { type: "application/pdf" }),
      { name: filename },
    ) as File;

    const upload = await uploadPrescriptionPdf(
      supabase,
      file,
      rx.patient_id,
      rx.id,
      rx.prescriber_id,
    );
    if (!upload.success || !upload.storagePath) {
      return { storagePath: currentStoragePath, regenerated: false, reason: `upload_failed:${upload.error}` };
    }

    // ── Content validation (Keith Robinson incident, May 8 2026) ──
    // The size check (HEALTHY_PDF_MIN_BYTES) catches image-only wrappers
    // but not "right-size, wrong-content" PDFs. The Robinson bug was a
    // 2.83 MB Electronic Rx whose drug name lacked the "AIM " prefix
    // because the prescription had no catalog medication_id, so
    // useGreenwichFormat fell through to false and the renderer printed
    // the raw `rx.medication` free-text field instead of the
    // formatDrugNameWithPrefix("AIM " + ...) string.
    //
    // Validate the inputs that actually go into the PDF and persist any
    // failure to prescriptions.pdf_validation_error so the admin badge
    // turns red. This is non-blocking — the order still ships per
    // Joseph's hard rule (May 8 2026: "nothing stops the order").
    const contentErrors: string[] = [];
    if (!catalogDrugName) {
      // No catalog medication → the renderer used raw rx.medication and
      // the printed name will NOT have the Greenwich-mandated "AIM " prefix.
      contentErrors.push("no_catalog_aim_prefix");
    }
    if (!patient.first_name || !patient.last_name) {
      contentErrors.push("patient_name_missing");
    }
    const validationError = contentErrors.length > 0 ? contentErrors.join(",") : null;
    // Always write — null on success CLEARS any prior error so a fixed
    // re-regen doesn't keep the badge red forever.
    await supabase
      .from("prescriptions")
      .update({ pdf_validation_error: validationError })
      .eq("id", prescriptionId);

    // uploadPrescriptionPdf already updates prescriptions.pdf_storage_path,
    // so we don't need to write it again. Audit the regen for traceability.
    await supabase.from("system_logs").insert({
      action: "PRESCRIPTION_PDF_AUTO_REGENERATED",
      status: validationError ? "warning" : "info",
      details: `prescriptionId=${prescriptionId} reason=${reasonTag} oldPath=${currentStoragePath} newPath=${upload.storagePath} newSizeBytes=${arrayBuffer.byteLength}${validationError ? ` validationError=${validationError}` : ""}`,
    });

    return { storagePath: upload.storagePath, regenerated: true, reason: "regenerated" };
  } catch (err) {
    return {
      storagePath: currentStoragePath,
      regenerated: false,
      reason: `exception:${err instanceof Error ? err.message : "unknown"}`,
    };
  }
}

/**
 * PDF HEALTH CHECK — Trevor Haynes incident, May 7 2026.
 *
 * Checks the size of a PDF in the patient-files storage bucket. Anything
 * below HEALTHY_PDF_MIN_BYTES is the bug pattern (image-only JPEG-in-PDF
 * wrapper from a provider's Step 1 file upload). Returns null if the
 * storage row can't be located (treated as unhealthy by callers).
 */
export async function getPdfSizeBytes(
  _supabase: SupabaseClient,
  storagePath: string,
): Promise<number | null> {
  // IMPORTANT (Blocker fix May 8 2026, architect review of "always sent
  // and always correct" gate): Supabase PostgREST only exposes the
  // `public` and `graphql_public` schemas — `.schema("storage")` returns
  // PGRST106 ("Invalid schema: storage") even with the service role.
  // The previous implementation here returned null for EVERY call in
  // prod, which made the hard-gate's pillar-1 size check fail for every
  // Greenwich submission and infinite-held all orders.
  //
  // We now read storage.objects via a direct postgres connection — the
  // same pattern proven in app/api/admin/prescriptions/route.ts for the
  // PDF health badge. One short-lived connection per call, closed in
  // finally so we don't leak under the 1-tick-per-minute janitor cohort
  // G load.
  if (!storagePath) return null;
  const dbUrl = process.env.SUPABASE_DATABASE_URL || process.env.DATABASE_URL;
  if (!dbUrl) {
    console.error("[getPdfSizeBytes] no SUPABASE_DATABASE_URL — returning null");
    return null;
  }
  let sql: ReturnType<typeof postgres> | null = null;
  try {
    sql = postgres(dbUrl, { max: 1, idle_timeout: 5, connect_timeout: 5 });
    const rows = await sql<{ size: string | number | null }[]>`
      SELECT (metadata->>'size')::bigint AS size
      FROM storage.objects
      WHERE bucket_id = 'patient-files'
        AND name = ${storagePath}
      LIMIT 1
    `;
    if (rows.length === 0) return null;
    const raw = rows[0].size;
    const n = typeof raw === "number" ? raw : raw != null ? Number(raw) : NaN;
    return Number.isFinite(n) ? n : null;
  } catch (err) {
    console.error(
      "[getPdfSizeBytes] direct postgres lookup threw (non-fatal):",
      err instanceof Error ? err.message : err,
    );
    return null;
  } finally {
    if (sql) {
      try { await sql.end({ timeout: 1 }); } catch { /* ignore */ }
    }
  }
}

/**
 * GREENWICH CONTENT VALIDATOR — Blocker fix May 8 2026.
 *
 * Loads the same row data `regenerateGreenwichPdfFromRow` consumes and
 * runs the SAME validation rules — but WITHOUT regenerating the PDF.
 * Used by the hard-gate in `submit-to-pharmacy-core.ts` to catch the
 * "right size, wrong content" case (Robinson — 2.83 MB PDF whose drug
 * name lacked the AIM prefix because the prescription had no catalog
 * `medication_id`). Previously `pdf_validation_error` was only ever
 * written by the regen path, so a freshly-uploaded healthy-sized PDF
 * with bad content slipped through.
 *
 * Returns the comma-joined error string (or null if all checks pass)
 * and ALSO writes it to `prescriptions.pdf_validation_error` so the
 * admin badge picks it up and a fixed re-run clears it.
 *
 * Mirrors `regenerateGreenwichPdfFromRow`'s validation rules exactly:
 *   - missing catalog drug → no_catalog_aim_prefix
 *   - missing patient name → patient_name_missing
 */
export async function validateGreenwichPdfContent(
  supabase: SupabaseClient,
  prescriptionId: string,
): Promise<string | null> {
  try {
    const { data: rx } = await supabase
      .from("prescriptions")
      .select("patient_id, medication_id")
      .eq("id", prescriptionId)
      .single();
    if (!rx) return null; // can't validate what we can't load — let the gate's
                          // pillar-2 (path) check handle the missing-row case
    let catalogDrugName: string | null = null;
    if (rx.medication_id) {
      const { data: med } = await supabase
        .from("pharmacy_medications")
        .select("name")
        .eq("id", rx.medication_id)
        .maybeSingle();
      catalogDrugName = med?.name ?? null;
    }
    const { data: patient } = await supabase
      .from("patients")
      .select("first_name, last_name")
      .eq("id", rx.patient_id)
      .single();

    const errs: string[] = [];
    // Same rule as regenerateGreenwichPdfFromRow: no catalog medication
    // → useGreenwichFormat falls through to false → printed name lacks
    // the AIM prefix Greenwich requires.
    if (!catalogDrugName) errs.push("no_catalog_aim_prefix");
    if (!patient?.first_name || !patient?.last_name) {
      errs.push("patient_name_missing");
    }
    const validationError = errs.length > 0 ? errs.join(",") : null;

    // Always write — null clears any prior error so a fixed re-check
    // doesn't keep the badge red forever.
    await supabase
      .from("prescriptions")
      .update({ pdf_validation_error: validationError })
      .eq("id", prescriptionId);

    return validationError;
  } catch (err) {
    console.error(
      "[validateGreenwichPdfContent] threw — failing CLOSED:",
      err instanceof Error ? err.message : err,
    );
    // FAIL-CLOSED (code review fix May 8 2026): Joseph's "always
    // correct" rule means we cannot let a transient validator query
    // error wave a bad PDF through pillar 3. Return a sentinel error
    // string so the hard-gate holds the row for cohort G to retry.
    // Don't WRITE the sentinel — leave the column at whatever it was
    // so a transient blip doesn't false-paint the admin badge red on
    // a row whose actual content is fine.
    return `validator_error:${err instanceof Error ? err.message.slice(0, 60) : "unknown"}`;
  }
}

/**
 * Health-check the prescription's stored PDF and FORCE-regenerate if it
 * looks like the Trevor-class image-only wrapper. Greenwich-only — we
 * can't know other pharmacies' format expectations here, so we leave
 * non-Greenwich submissions alone.
 *
 * NEVER blocks the caller's submission. If the file is unhealthy AND
 * regeneration also fails, returns the original path so the order still
 * goes out (Joseph's hard rule, May 8 2026: "nothing stops the order,
 * lives are at risk; auto-fix to green internally and ship"). The
 * unhealthy + un-regen-able case is logged loudly to system_logs as
 * PRESCRIPTION_PDF_HEAL_FAILED for operator follow-up.
 */
export async function ensureHealthyGreenwichPdf(
  supabase: SupabaseClient,
  prescriptionId: string,
  currentStoragePath: string | null,
  pharmacyId: string | null | undefined,
): Promise<StalePdfResult> {
  if (!pharmacyId || !isGreenwichPharmacy(pharmacyId)) {
    return { storagePath: currentStoragePath || "", regenerated: false, reason: "not_greenwich" };
  }
  if (!currentStoragePath) {
    // No PDF at all — try to build one from the row.
    const built = await regenerateGreenwichPdfFromRow(
      supabase,
      prescriptionId,
      "",
      "no_pdf_in_storage",
    );
    if (!built.regenerated) {
      await supabase.from("system_logs").insert({
        action: "PRESCRIPTION_PDF_HEAL_FAILED",
        status: "error",
        details: `prescriptionId=${prescriptionId} reason=no_pdf_and_regen_failed regenReason=${built.reason} — order still proceeding without PDF`,
      });
    }
    return built;
  }

  const sizeBytes = await getPdfSizeBytes(supabase, currentStoragePath);
  if (sizeBytes !== null && sizeBytes >= HEALTHY_PDF_MIN_BYTES) {
    return { storagePath: currentStoragePath, regenerated: false, reason: `healthy:${sizeBytes}b` };
  }

  // Bad / missing → force regen.
  const reasonTag = sizeBytes === null
    ? "storage_row_missing"
    : `image_only_size_${sizeBytes}b_below_${HEALTHY_PDF_MIN_BYTES}`;
  const result = await regenerateGreenwichPdfFromRow(
    supabase,
    prescriptionId,
    currentStoragePath,
    reasonTag,
  );
  if (!result.regenerated) {
    await supabase.from("system_logs").insert({
      action: "PRESCRIPTION_PDF_HEAL_FAILED",
      status: "error",
      details: `prescriptionId=${prescriptionId} reason=unhealthy_regen_failed origReason=${reasonTag} regenReason=${result.reason} — order still proceeding with original PDF`,
    });
  }
  return result;
}

export const _PDF_HEALTH_MIN_BYTES = HEALTHY_PDF_MIN_BYTES;
