export const WESTSIDE_CATEGORIES = [
  { name: "Weight Loss & Metabolism", slug: "weight-loss-metabolism", color: "#10B981", image: "cat-weight-loss.png", order: 1, desc: "GLP-1 receptor agonists, lipotropic injections, and metabolic support formulations for weight management." },
  { name: "GLP-1 & Weight Management", slug: "glp1-weight-management", color: "#059669", image: "cat-glp1.png", order: 2, desc: "Semaglutide, Tirzepatide, and other GLP-1/GIP receptor agonist injections for weight management." },
  { name: "Hormone Replacement Therapy (BHRT)", slug: "bhrt-hormone-therapy", color: "#8B5CF6", image: "cat-bhrt.png", order: 3, desc: "Bio-identical hormone replacement including estradiol, progesterone, testosterone, and DHEA formulations." },
  { name: "Sexual Health", slug: "sexual-health", color: "#3B82F6", image: "cat-sexual-health.png", order: 4, desc: "Tri-Mix injections, PDE5 inhibitors, and other compounded formulations for sexual wellness." },
  { name: "Topical Pain Management", slug: "topical-pain-management", color: "#F59E0B", image: "cat-topical-pain.png", order: 5, desc: "Custom compounded topical creams, gels, and ointments for targeted pain relief." },
  { name: "Pain Management & Anesthesia", slug: "pain-management-anesthesia", color: "#7C3AED", image: "cat-pain-management.png", order: 6, desc: "Ketamine troches, nasal sprays, and other compounded pain and anesthesia formulations." },
  { name: "Dermatology & Skin Care", slug: "dermatology-skin-care", color: "#EC4899", image: "cat-dermatology.png", order: 7, desc: "Compounded dermatological preparations including anti-aging creams, antiviral topicals, and skin treatments." },
  { name: "Anti-Inflammatory & Healing", slug: "anti-inflammatory-healing", color: "#EAB308", image: "cat-anti-inflammatory.png", order: 8, desc: "Anti-inflammatory peptides and healing compounds for tissue repair and recovery." },
  { name: "Hospice & Palliative Care", slug: "hospice-palliative-care", color: "#A78BFA", image: "cat-hospice.png", order: 9, desc: "Compounded formulations for comfort care including ABH/ABHR topicals and suppositories." },
  { name: "Women's Health", slug: "womens-health", color: "#F472B6", image: "cat-womens-health.png", order: 10, desc: "Vaginal compounds, nipple ointments, and other women's health formulations." },
  { name: "Low-Dose Naltrexone (LDN)", slug: "low-dose-naltrexone", color: "#6366F1", image: "cat-ldn.png", order: 11, desc: "Low-dose naltrexone capsules for immune modulation and chronic pain management." },
  { name: "NAD+ & Biohacking", slug: "nad-biohacking", color: "#14B8A6", image: "cat-nad-biohacking.png", order: 12, desc: "NAD+ therapy and cellular optimization formulations for anti-aging and energy support." },
  { name: "Cardiac & Cardiovascular", slug: "cardiac-cardiovascular", color: "#DC2626", image: "cat-cardiac.png", order: 13, desc: "Compounded cardiac medications including oral suspensions for cardiovascular health." },
  { name: "Veterinary Compounding", slug: "veterinary-compounding", color: "#65A30D", image: "cat-veterinary.png", order: 14, desc: "Compounded medications for veterinary patients including transdermal and oral formulations." },
  { name: "Gastrointestinal & Rectal", slug: "gastrointestinal-rectal", color: "#92400E", image: "cat-gastrointestinal.png", order: 15, desc: "Rectal rockets, diltiazem, nifedipine, and other GI compounded preparations." },
  { name: "Ear, Nose & Throat", slug: "ear-nose-throat", color: "#0EA5E9", image: "cat-ent.png", order: 16, desc: "Otic preparations, nasal rinses, and ENT compounded formulations." },
  { name: "Oral Care", slug: "oral-care", color: "#2DD4BF", image: "cat-oral-care.png", order: 17, desc: "Magic mouthwash and other compounded oral rinse formulations." },
  { name: "Mental Health", slug: "mental-health", color: "#818CF8", image: "cat-mental-health.png", order: 18, desc: "Compounded mental health medications including oral suspensions." },
  { name: "Anti-Nausea", slug: "anti-nausea", color: "#4ADE80", image: "cat-anti-nausea.png", order: 19, desc: "Compounded anti-nausea formulations for symptom management." },
  { name: "Cognitive & Cellular Health", slug: "cognitive-cellular-health", color: "#38BDF8", image: "cat-cognitive.png", order: 20, desc: "Methylene blue and other cognitive enhancement formulations." },
  { name: "Hair Restoration", slug: "hair-restoration", color: "#854D0E", image: "cat-hair-restoration.png", order: 21, desc: "Compounded hair loss treatments including minoxidil combinations and topical formulations." },
  { name: "Vitamins & Supplements", slug: "vitamins-supplements", color: "#F97316", image: "cat-vitamins.png", order: 22, desc: "Compounded vitamin injections and supplement formulations." },
  { name: "Oral Suspensions", slug: "oral-suspensions", color: "#64748B", image: "cat-compounding.png", order: 23, desc: "Custom compounded oral suspensions for patients who cannot swallow tablets." },
  { name: "Compounding Specialties", slug: "compounding-specialties", color: "#1E3A5F", image: "cat-compounding.png", order: 24, desc: "Specialty compounded formulations and custom preparations." },
];
